[[pages]]
path = "./pages/app.py"
name = "Home"
icon = ":house:"

[[pages]]
name = "Contents"
icon = ":books:"
is_section = true

[[pages]]
path = "./pages/problem.py"
name = "Problem Statement"
icon = "ğŸ“–"

[[pages]]
path = "./pages/objective.py"
name = "Objective"
icon = "ğŸ¯"

[[pages]]
path = "./pages/architecture_old.py"
name = "Feasiblity Study | Early Architecture"
icon = "1ï¸âƒ£"

[[pages]]
path = "./pages/block.py"
name = "Feasiblity Study | Functional Block"
icon = "2ï¸âƒ£"

[[pages]]
path = "./pages/question_answer_1.py"
name = "Feasibility Study | Q&A "
icon = "3ï¸âƒ£"

[[pages]]
path = "./pages/question_answer_2.py"
name = "Feasibility Study | Q&A"
icon = "4ï¸âƒ£"

[[pages]]
path = "./pages/question_answer_3.py"
name = "Feasibility Study | Q&A"
icon = "5ï¸âƒ£"

[[pages]]
path = "./pages/question_answer_4.py"
name = "Feasibility Study | Q&A"
icon = "6ï¸âƒ£"

[[pages]]
path = "./pages/inprogress.py"
name = "In Progress"
icon = "âŒ›"

[[pages]]
path = "./pages/helpneeded.py"
name = "Help Needed"
icon = "ğŸ› ï¸"

[[pages]]
name = "Wiki Search"
icon = "ğŸš€"
is_section = true

[[pages]]
path = "./pages/wiki_v1_0.py"
name = "Wiki v1.0"
icon = "âš¡"

[[pages]]
path = "./pages/wiki_v2_0.py"
name = "Wiki v2.0"
icon = "âš¡"

[[pages]]
path = "./pages/wiki_v3_0.py"
name = "Wiki v3.0"
icon = "âš¡"

[[pages]]
path = "./pages/chatbot_retrievalqa.py"
name = "X-Chat - RAG (Retrieval QA)"
icon = "ğŸ¤–"

[[pages]]
path = "./pages/chatbot_loadqa.py"
name = "X-Chat - RAG (Load Chain Retrieval QA)"
icon = "ğŸ¤–"

[[pages]]
path = "./pages/chatbot_conversational.py"
name = "X-Chat - RAG (Conversational Retrieval QA)"
icon = "ğŸ¤–"

[[pages]]
path = "./pages/finetuning.py"
name = "Fine-Tuning Method"
icon = "ğŸ—ï¸"
in_section = false

[[pages]]
path = "./pages/info.py"
name = "About"
icon = "ğŸ“¢"
in_section = false